language: node_js

services:
  - docker

before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.22.0-1

cache:
  yarn: true

install:
  - yarn --silent
  - yarn workspace @endnote/common run build

script:
  - yarn run test
  - yarn run coverage
  - yarn run lint

before_deploy:
  - docker build -f packages/backend/Dockerfile -t endnote/backend:${TRAVIS_TAG} .
  - docker build -f packages/frontend/Dockerfile -t endnote/frontend:${TRAVIS_TAG} .

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    tags: true
