#
# This docker-compose file is intended for development only.
# Do not use this in production!
#

version: '2'

services:
  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=securenote

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
      args:
        - NODE_ENV=development
        - COMMAND=dev
    restart: always
    env_file:
      - .env
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    volumes:
      - ./packages/backend/src:/app/packages/backend/src

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
      args:
        - NODE_ENV=development
        - COMMAND=dev
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - PORT=8001
    ports:
      - 8001:8001
    links:
      - postgres:postgres
    volumes:
      - ./packages/frontend/src:/app/packages/frontend/src

volumes:
  postgres-data:
